services:
  - type: web
    name: contacts-api
    env: node
    rootDir: project1
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: YOUR_MONGODB_URI_HERE
